package com.mini.store.demo.dao;

import com.mini.store.demo.model.Delivery;

public interface DeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    int deleteByPrimaryKey(Integer deliveryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    int insert(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    int insertSelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    Delivery selectByPrimaryKey(Integer deliveryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    int updateByPrimaryKeySelective(Delivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveries
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    int updateByPrimaryKey(Delivery record);
}