package com.mini.store.demo.dao;

import com.mini.store.demo.model.ItemStock;

public interface ItemStockMapper {
    ItemStock selectByItemId(Integer itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    int insertSelective(ItemStock record);
}