package com.mini.store.demo.dao;

import com.mini.store.demo.model.OrderItemAssociation;

public interface OrderItemAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_items
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    int insert(OrderItemAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_items
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    int insertSelective(OrderItemAssociation record);
}