server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*.xml


spring:
  datasource:
    name: mini_store
    url: jdbc:mysql://localhost:3306/mini_store
    username: root
    password: password
#druid datasource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#https://www.jianshu.com/p/3624159ae0bf
    druid:
      wall:
        config:
          variantCheck: false
          noneBaseStatementAllow: true
          commentAllow: true
          multiStatementAllow: true
#热部署配置enable
  devtools:
    restart:
      enabled: true
      #监听目录
      additional-paths: src/main/java

  #https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
  flyway:
    baseline-on-migrate: true
#    user: root
#    password: password
#    schemas: mini_store
#    url: jdbc:mysql://localhost:3306/mini_store
##Locations of migrations scripts.
##classpath:db/migration means mini-store-api/src/main/resources/db/migration
#    locations: classpath:db/migration
#    enabled: true

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  #30 days
  expiresSecond: 2592000000

wx:
  miniapp:
    appid: wx5c00a4bf5e176be4
    secret: 88f59d8eb532d115d6b28b86fea81926
    msgDataFormat: JSON


logging:
  level:
    com: debug
  file:
    name: 'app.log'


