package com.mini.store.demo.model;

public class Delivery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private Integer deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_name
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_phone
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_address
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_province
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_city
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.delivery_district
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private String deliveryDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveries.order_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_id
     *
     * @return the value of deliveries.delivery_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_id
     *
     * @param deliveryId the value for deliveries.delivery_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_name
     *
     * @return the value of deliveries.delivery_name
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryName() {
        return deliveryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_name
     *
     * @param deliveryName the value for deliveries.delivery_name
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName == null ? null : deliveryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_phone
     *
     * @return the value of deliveries.delivery_phone
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryPhone() {
        return deliveryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_phone
     *
     * @param deliveryPhone the value for deliveries.delivery_phone
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryPhone(String deliveryPhone) {
        this.deliveryPhone = deliveryPhone == null ? null : deliveryPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_address
     *
     * @return the value of deliveries.delivery_address
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_address
     *
     * @param deliveryAddress the value for deliveries.delivery_address
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress == null ? null : deliveryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_province
     *
     * @return the value of deliveries.delivery_province
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryProvince() {
        return deliveryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_province
     *
     * @param deliveryProvince the value for deliveries.delivery_province
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryProvince(String deliveryProvince) {
        this.deliveryProvince = deliveryProvince == null ? null : deliveryProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_city
     *
     * @return the value of deliveries.delivery_city
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryCity() {
        return deliveryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_city
     *
     * @param deliveryCity the value for deliveries.delivery_city
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryCity(String deliveryCity) {
        this.deliveryCity = deliveryCity == null ? null : deliveryCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.delivery_district
     *
     * @return the value of deliveries.delivery_district
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public String getDeliveryDistrict() {
        return deliveryDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.delivery_district
     *
     * @param deliveryDistrict the value for deliveries.delivery_district
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setDeliveryDistrict(String deliveryDistrict) {
        this.deliveryDistrict = deliveryDistrict == null ? null : deliveryDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveries.order_id
     *
     * @return the value of deliveries.order_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveries.order_id
     *
     * @param orderId the value for deliveries.order_id
     *
     * @mbg.generated Wed Apr 01 00:24:48 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}