package com.mini.store.demo.model;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_price
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Long itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_price_unit
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String itemPriceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_description
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String itemDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_sales
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer itemSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_img_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String itemImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.category
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String category;

    private ItemStock itemStock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_id
     *
     * @return the value of items.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_id
     *
     * @param itemId the value for items.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_name
     *
     * @return the value of items.item_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_name
     *
     * @param itemName the value for items.item_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_price
     *
     * @return the value of items.item_price
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Long getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_price
     *
     * @param itemPrice the value for items.item_price
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemPrice(Long itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_price_unit
     *
     * @return the value of items.item_price_unit
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getItemPriceUnit() {
        return itemPriceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_price_unit
     *
     * @param itemPriceUnit the value for items.item_price_unit
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemPriceUnit(String itemPriceUnit) {
        this.itemPriceUnit = itemPriceUnit == null ? null : itemPriceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_description
     *
     * @return the value of items.item_description
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_description
     *
     * @param itemDescription the value for items.item_description
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription == null ? null : itemDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_sales
     *
     * @return the value of items.item_sales
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getItemSales() {
        return itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_sales
     *
     * @param itemSales the value for items.item_sales
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemSales(Integer itemSales) {
        this.itemSales = itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_img_url
     *
     * @return the value of items.item_img_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getItemImgUrl() {
        return itemImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_img_url
     *
     * @param itemImgUrl the value for items.item_img_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemImgUrl(String itemImgUrl) {
        this.itemImgUrl = itemImgUrl == null ? null : itemImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.user_id
     *
     * @return the value of items.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.user_id
     *
     * @param userId the value for items.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.create_date
     *
     * @return the value of items.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.create_date
     *
     * @param createDate the value for items.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.update_date
     *
     * @return the value of items.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.update_date
     *
     * @param updateDate the value for items.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.category
     *
     * @return the value of items.category
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.category
     *
     * @param category the value for items.category
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}
