package com.mini.store.demo.model;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.name
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.price
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.price_unit
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private String priceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.description
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.sales
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.img_url
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.user_id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.create_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.update_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.category
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    private String category;

    private ItemStock itemStock;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.id
     *
     * @return the value of items.id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.id
     *
     * @param id the value for items.id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.name
     *
     * @return the value of items.name
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.name
     *
     * @param name the value for items.name
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.price
     *
     * @return the value of items.price
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.price
     *
     * @param price the value for items.price
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.price_unit
     *
     * @return the value of items.price_unit
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.price_unit
     *
     * @param priceUnit the value for items.price_unit
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.description
     *
     * @return the value of items.description
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.description
     *
     * @param description the value for items.description
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.sales
     *
     * @return the value of items.sales
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.sales
     *
     * @param sales the value for items.sales
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.img_url
     *
     * @return the value of items.img_url
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.img_url
     *
     * @param imgUrl the value for items.img_url
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.user_id
     *
     * @return the value of items.user_id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.user_id
     *
     * @param userId the value for items.user_id
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.create_date
     *
     * @return the value of items.create_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.create_date
     *
     * @param createDate the value for items.create_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.update_date
     *
     * @return the value of items.update_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.update_date
     *
     * @param updateDate the value for items.update_date
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.category
     *
     * @return the value of items.category
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.category
     *
     * @param category the value for items.category
     *
     * @mbg.generated Sat Mar 07 23:34:52 CST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }


}
