package com.mini.store.demo.model;

import java.util.Date;

public class ItemStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.item_stock
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer itemStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.item_stock
     *
     * @return the value of item_stock.item_stock
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getItemStock() {
        return itemStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.item_stock
     *
     * @param itemStock the value for item_stock.item_stock
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemStock(Integer itemStock) {
        this.itemStock = itemStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.item_id
     *
     * @return the value of item_stock.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.item_id
     *
     * @param itemId the value for item_stock.item_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.create_date
     *
     * @return the value of item_stock.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.create_date
     *
     * @param createDate the value for item_stock.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.update_date
     *
     * @return the value of item_stock.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.update_date
     *
     * @param updateDate the value for item_stock.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}