package com.mini.store.demo.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_amount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.discount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Long discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_amount
     *
     * @return the value of orders.total_amount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_amount
     *
     * @param totalAmount the value for orders.total_amount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.discount
     *
     * @return the value of orders.discount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Long getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.discount
     *
     * @param discount the value for orders.discount
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_date
     *
     * @return the value of orders.create_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_date
     *
     * @param createDate the value for orders.create_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_date
     *
     * @return the value of orders.update_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_date
     *
     * @param updateDate the value for orders.update_date
     *
     * @mbg.generated Sun Mar 08 02:18:11 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}