package com.mini.store.demo.model;

public class Transaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_agent
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private String transactionAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_account
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private String transactionAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_type
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private String transactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_amount
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private Long transactionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.transaction_status
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private String transactionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.order_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_id
     *
     * @return the value of transactions.transaction_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_id
     *
     * @param transactionId the value for transactions.transaction_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_agent
     *
     * @return the value of transactions.transaction_agent
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public String getTransactionAgent() {
        return transactionAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_agent
     *
     * @param transactionAgent the value for transactions.transaction_agent
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionAgent(String transactionAgent) {
        this.transactionAgent = transactionAgent == null ? null : transactionAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_account
     *
     * @return the value of transactions.transaction_account
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public String getTransactionAccount() {
        return transactionAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_account
     *
     * @param transactionAccount the value for transactions.transaction_account
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionAccount(String transactionAccount) {
        this.transactionAccount = transactionAccount == null ? null : transactionAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_type
     *
     * @return the value of transactions.transaction_type
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_type
     *
     * @param transactionType the value for transactions.transaction_type
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_amount
     *
     * @return the value of transactions.transaction_amount
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public Long getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_amount
     *
     * @param transactionAmount the value for transactions.transaction_amount
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionAmount(Long transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.transaction_status
     *
     * @return the value of transactions.transaction_status
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.transaction_status
     *
     * @param transactionStatus the value for transactions.transaction_status
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus == null ? null : transactionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.order_id
     *
     * @return the value of transactions.order_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.order_id
     *
     * @param orderId the value for transactions.order_id
     *
     * @mbg.generated Thu Apr 02 21:30:14 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}