package com.mini.store.demo.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_role
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.encrpt_password
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String encrptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wechat_open_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String wechatOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_avatar_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private String userAvatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_role
     *
     * @return the value of users.user_role
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_role
     *
     * @param userRole the value for users.user_role
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.encrpt_password
     *
     * @return the value of users.encrpt_password
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getEncrptPassword() {
        return encrptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.encrpt_password
     *
     * @param encrptPassword the value for users.encrpt_password
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setEncrptPassword(String encrptPassword) {
        this.encrptPassword = encrptPassword == null ? null : encrptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone
     *
     * @return the value of users.phone
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone
     *
     * @param phone the value for users.phone
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wechat_open_id
     *
     * @return the value of users.wechat_open_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getWechatOpenId() {
        return wechatOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wechat_open_id
     *
     * @param wechatOpenId the value for users.wechat_open_id
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId == null ? null : wechatOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_avatar_url
     *
     * @return the value of users.user_avatar_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public String getUserAvatarUrl() {
        return userAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_avatar_url
     *
     * @param userAvatarUrl the value for users.user_avatar_url
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUserAvatarUrl(String userAvatarUrl) {
        this.userAvatarUrl = userAvatarUrl == null ? null : userAvatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_date
     *
     * @return the value of users.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_date
     *
     * @param createDate the value for users.create_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_date
     *
     * @return the value of users.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_date
     *
     * @param updateDate the value for users.update_date
     *
     * @mbg.generated Sun Mar 08 17:44:28 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}